diffusion_params:
  beta_start : 1.0e-4
  beta_end : 0.02
  num_timesteps : 500

dataset_params:
  im_path:
  module_name: 'datasets.mnist_diffusion_dataset'
  name: 'MnistDiffusionDataset'

unet_params:
  in_channels: 3
  out_channels: [128, 256]
  t_emb_dim: 512
  num_heads: 8
  num_norm_groups: 32
  num_down_blocks: 2
  num_mid_blocks: 3
  use_context: False

training_params:
  device: 'mps'
  loss: 'MSELoss'
  scheduler: 'LinearLR'
  scheduler_params:
    start_factor: 0.05
    end_factor: 1
    total_iters: 30000
  optimizer: 'Adam'
  opt_params:
    lr: 0.0003
    weight_decay: 0
  batch_size: 64
  num_steps: 1000
  epochs: 1
  save_checkpoint: './models/weights/ckpt.pt'




